apiVersion: v1
kind: Service
metadata:
  name: dummy-producer
  namespace: kafka
spec:
  selector:
    app: dummy-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP