
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etl-consumer
  namespace: kafka
spec:
  serviceName: "etl-consumer"
  replicas: 1
  selector:
    matchLabels:
      app: etl-consumer
  template:
    metadata:
      labels:
        app: etl-consumer
    spec:
      containers:
        - name: etl-consumer
          image: etl-consumer:latest
          imagePullPolicy: IfNotPresent
        - name: kafka-cli
          image: docker.io/bitnami/kafka:3.6.1
          command: [ "sleep" ]
          args: [ "infinity" ]
        - name: mongo-cli
          image: mongo:7.0
          command: [ "sleep" ]
          args: [ "infinity" ]
