FROM bitnami/kafka:3.6.0

USER root

# Install supported debug tools only
RUN install_packages \
    bash \
    curl \
    net-tools \
    iputils-ping \
    dnsutils \
    netcat \
    iproute2 \
    vim

USER 1001

ENTRYPOINT [ "sleep", "3600" ]
